"""Add audio_file column to Script model

Revision ID: 11cc575f4743
Revises: 69cc859c97bb
Create Date: 2024-10-17 14:36:11.405347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cc575f4743'
down_revision = '69cc859c97bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script', schema=None) as batch_op:
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###
